# Generated by Django 5.2.17 on 2026-08-20 10:30

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        ('core', '0030_operator_enforce_staff_2fa'),
    ]

    operations = [
        # The pgvector type must exist before any VectorField column is created.
        VectorExtension(),
        migrations.CreateModel(
            name='DocChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='docchunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('slug', 'ordinal'), name='docchunk_slug_ordinal')],
            },
        ),
        migrations.CreateModel(
            name='AssistantQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('grounded', models.BooleanField(default=False)),
                ('top_score', models.FloatField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=60)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_questions', to='core.operator')),
            ],
            options={
                'indexes': [models.Index(fields=['grounded', 'created_at'], name='assistant_a_grounde_d40339_idx')],
            },
        ),
    ]
