# Generated by Django 5.2.17 on 2026-08-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_docchunk_assistantquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='pro_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistantquestion',
            name='tokens_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistantquestion',
            name='tokens_out',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
