# Generated by Django 5.2.17 on 2026-08-20 12:00

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_aisettings_pro_ai_assistantquestion_tokens_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('openai', 'OpenAI')], default='claude', max_length=10)),
                ('api_key', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('rate_limit_per_min', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
