# Generated by Django 5.2.17 on 2026-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_conversation_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantquestion',
            name='model',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='assistantquestion',
            name='tier',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
