# Generated by Django 5.2.16 on 2026-07-11 20:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_operator_county_operator_referral_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupThrottle',
            fields=[
                ('key', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SignupApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('resends', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('county', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('referral_source', models.CharField(blank=True, max_length=40)),
                ('tos_version', models.CharField(blank=True, max_length=20)),
                ('tos_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('operator', models.OneToOneField(blank=True, help_text='Set when the draft becomes a real ISP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_application', to='core.operator')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='signup_sign_email_7db5a6_idx')],
            },
        ),
    ]
