# Generated by Django 5.2.16 on 2026-07-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operator_approved_at_operator_base_fee_and_more'),
        ('notifications', '0002_campaign_subject_message_subject_message_to_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator'),
        ),
        migrations.AlterField(
            model_name='message',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator'),
        ),
    ]
