# Generated by Django 5.2.16 on 2026-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_campaign_operator_alter_message_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('campaign', 'Marketing campaign'), ('payment', 'Payment confirmation'), ('expiry', 'Expiry warning'), ('pppoe', 'PPPoE notice'), ('other', 'Other')], db_index=True, default='campaign', max_length=12),
        ),
    ]
