# Generated by Django 5.2.16 on 2026-07-13 18:38

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_branding'),
        ('notifications', '0004_message_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_mode', models.CharField(choices=[('platform', 'Use the WIFI.OS platform gateway'), ('own', 'Use my own gateway')], default='platform', max_length=10)),
                ('sms_username', models.CharField(blank=True, max_length=100)),
                ('sms_api_key', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('sms_sender_id', models.CharField(blank=True, max_length=11)),
                ('email_mode', models.CharField(choices=[('platform', 'Use the WIFI.OS platform gateway'), ('own', 'Use my own gateway')], default='platform', max_length=10)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=80)),
                ('whatsapp_mode', models.CharField(choices=[('off', 'Disabled'), ('own', 'Use my own gateway')], default='off', max_length=10)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=50)),
                ('whatsapp_token', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging', to='core.operator')),
            ],
        ),
    ]
