# Generated by Django 5.2.16 on 2026-07-13 19:37

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_branding'),
        ('notifications', '0005_messagingsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagingsettings',
            name='sms_api_key',
        ),
        migrations.RemoveField(
            model_name='messagingsettings',
            name='sms_mode',
        ),
        migrations.RemoveField(
            model_name='messagingsettings',
            name='sms_sender_id',
        ),
        migrations.RemoveField(
            model_name='messagingsettings',
            name='sms_username',
        ),
        migrations.RemoveField(
            model_name='messagingsettings',
            name='whatsapp_mode',
        ),
        migrations.RemoveField(
            model_name='messagingsettings',
            name='whatsapp_phone_number_id',
        ),
        migrations.RemoveField(
            model_name='messagingsettings',
            name='whatsapp_token',
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='sms_provider',
            field=models.CharField(default='wifios', max_length=20),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='whatsapp_provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=10)),
                ('provider', models.CharField(max_length=20)),
                ('secrets', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to='core.operator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operator', 'channel', 'provider'), name='one_credential_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='SmsCreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credits', models.IntegerField()),
                ('reason', models.CharField(choices=[('purchase', 'Credits bought'), ('send', 'Message sent'), ('refund', 'Refund'), ('grant', 'Granted by the platform')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='notifications.message')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operator', 'created_at'], name='notificatio_operato_4d3ffd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('message',), name='one_credit_debit_per_message')],
            },
        ),
    ]
