# Generated by Django 5.2.16 on 2026-07-13 21:28

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_backfill_welcome_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='alert_phones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='low_balance_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('campaign', 'Marketing campaign'), ('payment', 'Payment confirmation'), ('expiry', 'Expiry warning'), ('pppoe', 'PPPoE notice'), ('alert', 'Platform alert to the ISP'), ('other', 'Other')], db_index=True, default='campaign', max_length=12),
        ),
    ]
