# Generated by Django 5.2.16 on 2026-07-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_branding_background_image_branding_portal_language_and_more'),
        ('notifications', '0010_messagetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_alerts_enabled', models.BooleanField(default=False)),
                ('router_alert_phones', models.JSONField(blank=True, default=list)),
                ('prefer_whatsapp', models.BooleanField(default=False)),
                ('compensate_outages', models.BooleanField(default=False)),
                ('sales_digest_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='core.operator')),
            ],
        ),
    ]
