# Generated by Django 5.2.16 on 2026-07-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriber'),
        ('ops', '0002_alter_equipment_operator_alter_expense_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.subscriber'),
        ),
    ]
