# Generated by Django 5.2.17 on 2026-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_ticket_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
