# Generated by Django 5.2.17 on 2026-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_lead_gps_lat_lead_gps_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
