# Generated by Django 5.2.16 on 2026-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat KSh/month for the subdomain', max_digits=10),
        ),
        migrations.AddField(
            model_name='operator',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='operator',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='operator',
            name='hotspot_commission_pct',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='% of hotspot revenue', max_digits=4),
        ),
        migrations.AddField(
            model_name='operator',
            name='owner_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='operator',
            name='pppoe_user_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='KSh per active PPPoE user/month', max_digits=10),
        ),
        migrations.AddField(
            model_name='operator',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=10),
        ),
    ]
