# Generated by Django 5.2.16 on 2026-07-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activate_existing_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='is_platform_owned',
            field=models.BooleanField(default=False, help_text="Platform's own ISP: exempt from all commission and platform fees."),
        ),
    ]
