# Generated by Django 5.2.16 on 2026-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operator_is_platform_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='payout_bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='operator',
            name='payout_bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='operator',
            name='payout_bank_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='operator',
            name='payout_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
