# Generated by Django 5.2.16 on 2026-07-11 10:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_operator_payout_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Flat KSh/month for the subdomain', max_digits=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='pppoe_user_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='KSh per active PPPoE user/month', max_digits=10),
        ),
    ]
