# Generated by Django 5.2.16 on 2026-07-11 11:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_operator_base_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='One-time onboarding fee, billed once when the ISP is approved', max_digits=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), help_text='Flat KSh/month for the subdomain', max_digits=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='pppoe_user_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='KSh per active PPPoE user/month; 0 = use platform volume tiers', max_digits=10),
        ),
    ]
