# Generated by Django 5.2.16 on 2026-07-11 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_operator_setup_fee_alter_operator_base_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='trial_ends_at',
            field=models.DateField(blank=True, help_text='Base fee is waived up to and including this date', null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Flat KSh/month for the subdomain (waived during the free trial)', max_digits=10),
        ),
    ]
