# Generated by Django 5.2.16 on 2026-07-11 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operator_trial_ends_at_alter_operator_base_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Why this access was needed', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Explicitly exited', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['operator', '-created_at'], name='core_auditl_operato_53b6b0_idx'),
        ),
        migrations.AddField(
            model_name='impersonationgrant',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationgrant',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations', to='core.operator'),
        ),
        migrations.AddIndex(
            model_name='impersonationgrant',
            index=models.Index(fields=['actor', 'operator', 'expires_at'], name='core_impers_actor_i_b0ad79_idx'),
        ),
    ]
