# Generated by Django 5.2.16 on 2026-07-11 20:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_impersonationgrant_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='county',
            field=models.CharField(blank=True, help_text='County of operation', max_length=40),
        ),
        migrations.AddField(
            model_name='operator',
            name='referral_source',
            field=models.CharField(blank=True, help_text='How they heard about us', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='operator',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='operator_name_unique_ci'),
        ),
    ]
