# Generated by Django 5.2.16 on 2026-07-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_operator_county_operator_referral_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='daraja_consumer_key',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='daraja_consumer_secret',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='mpesa_passkey',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='mpesa_shortcode',
        ),
        migrations.AddField(
            model_name='operator',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('paybill', 'M-Pesa Paybill (B2B)'), ('bank', 'Bank account (Pesalink/EFT)')], max_length=8),
        ),
        migrations.AddField(
            model_name='operator',
            name='settlement_name',
            field=models.CharField(blank=True, help_text='Registered name on the account', max_length=120),
        ),
        migrations.AddField(
            model_name='operator',
            name='settlement_paybill',
            field=models.CharField(blank=True, help_text='Their OWN paybill — we send money TO it', max_length=20),
        ),
        migrations.AddField(
            model_name='operator',
            name='settlement_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='verification_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operator',
            name='verification_ref',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='operator',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
