# Generated by Django 5.2.16 on 2026-07-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_operator_daraja_consumer_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='verification_amount',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='verification_ref',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='verification_sent_at',
        ),
        migrations.AlterField(
            model_name='operator',
            name='settlement_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the ISP confirmed a payout actually landed', null=True),
        ),
    ]
