# Generated by Django 5.2.16 on 2026-07-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_operator_verification_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='change_code_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operator',
            name='change_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='change_code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='operator',
            name='change_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
