# Generated by Django 5.2.16 on 2026-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_operator_change_code_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='notify_customers_sms',
            field=models.BooleanField(default=True),
        ),
    ]
