# Generated by Django 5.2.16 on 2026-07-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_operator_notify_customers_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('logo', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#141414', max_length=7)),
                ('accent_color', models.CharField(default='#228B22', max_length=7)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='core.operator')),
            ],
            options={
                'db_table': 'core_branding',
            },
        ),
    ]
