# Generated by Django 5.2.16 on 2026-07-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='previous_slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='operator',
            name='slug_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
