# Generated by Django 5.2.16 on 2026-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_operator_payment_gateway_and_webhook_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='billing_warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='credit_limit_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
