# Generated by Django 5.2.16 on 2026-07-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_operator_billing_warned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
