# Generated by Django 5.2.16 on 2026-07-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_operator_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='background_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branding',
            name='portal_language',
            field=models.CharField(default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='branding',
            name='portal_template',
            field=models.CharField(default='lumen', max_length=32),
        ),
        migrations.AddField(
            model_name='branding',
            name='post_purchase_redirect',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='HotspotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_start_mode', models.CharField(choices=[('on_purchase', 'On successful purchase'), ('on_login', 'On first Wi-Fi login')], default='on_purchase', max_length=16)),
                ('inactive_prune_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('username_prefix', models.CharField(blank=True, max_length=8)),
                ('voucher_expiry_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_settings', to='core.operator')),
            ],
        ),
    ]
