# Generated by Django 5.2.16 on 2026-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_branding_background_image_branding_portal_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='settlement_paybill_account',
            field=models.CharField(blank=True, help_text='Account number to credit at that paybill', max_length=40),
        ),
    ]
