# Generated by Django 5.2.16 on 2026-08-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_operator_settlement_paybill_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='payout_phone',
            field=models.CharField(blank=True, help_text='M-Pesa number we send your payout to', max_length=12),
        ),
        migrations.AlterField(
            model_name='operator',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa (phone number)'), ('paybill', 'M-Pesa Paybill (B2B)'), ('bank', 'Bank account (Pesalink/EFT)')], max_length=8),
        ),
        migrations.AlterField(
            model_name='operator',
            name='settlement_name',
            field=models.CharField(blank=True, help_text='Account name — business or personal (small ISPs often use a personal name)', max_length=120),
        ),
    ]
