# Generated by Django 5.2.16 on 2026-08-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_operator_payout_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Read-only showcase tenant: fully seeded, but the API refuses every write so anyone can explore WIFI.OS without changing data.'),
        ),
    ]
