# Generated by Django 5.2.17 on 2026-08-14 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_operator_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('event', models.CharField(choices=[('activated', 'Activated'), ('suspended', 'Suspended (left / cut off)'), ('reactivated', 'Reactivated (won back)')], db_index=True, max_length=15)),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(blank=True, max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to='core.operator')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event', 'occurred_at'], name='core_tenant_event_4fe4f8_idx'), models.Index(fields=['operator', 'occurred_at'], name='core_tenant_operato_9e3472_idx')],
            },
        ),
    ]
