# Generated by Django 5.2.17 on 2026-08-14 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_backfill_tenant_activation_anchors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantlifecycleevent',
            name='event',
            field=models.CharField(choices=[('activated', 'Activated'), ('suspended', 'Suspended (left / cut off)'), ('reactivated', 'Reactivated (won back)'), ('cancelled', 'Cancelled (offboarded — terminal)')], db_index=True, max_length=15),
        ),
        migrations.CreateModel(
            name='TenantOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled (in grace window)'), ('completed', 'Completed (terminal)'), ('aborted', 'Aborted (reinstated)')], db_index=True, default='scheduled', max_length=10)),
                ('reason', models.CharField(max_length=200)),
                ('initiated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grace_until', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_withdrawable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('snapshot_owed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subscribers_torn_down', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboardings', to='core.operator')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'scheduled')), fields=('operator',), name='one_active_offboarding_per_operator')],
            },
        ),
    ]
