# Generated by Django 5.2.17 on 2026-08-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_platformbroadcast_broadcastdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantoffboarding',
            name='fees_recovered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantoffboarding',
            name='net_settlement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantoffboarding',
            name='residual_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
