# Generated by Django 5.2.17 on 2026-08-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_operator_gps_lat_operator_gps_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='enforce_staff_2fa',
            field=models.BooleanField(default=False, help_text='When on, every employee of this ISP must enrol an authenticator before using the console. Optional org-wide switch — money actions are already owner + TOTP.'),
        ),
    ]
