# Generated by Django 5.2.16 on 2026-07-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('plan_type', models.CharField(choices=[('hotspot', 'Hotspot (prepaid)'), ('pppoe', 'PPPoE (monthly)')], default='hotspot', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField(help_text='Access time granted, e.g. 1:00:00 for one hour')),
                ('data_cap_mb', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited data', null=True)),
                ('download_kbps', models.PositiveIntegerField()),
                ('upload_kbps', models.PositiveIntegerField()),
                ('shared_users', models.PositiveSmallIntegerField(default=1)),
                ('mikrotik_profile', models.CharField(default='default', help_text='Hotspot user profile name on the router', max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.operator')),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
