# Generated by Django 5.2.16 on 2026-07-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tv_slots',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
