/**
 * Typed API client. Model types come from the OpenAPI schema generated by the
 * backend (`npm run generate:api` after `manage.py spectacular --file schema.yml`),
 * so the portal can never silently drift from the server contract.
 */

import type { components } from './schema';

export type Plan = components['schemas']['Plan'];

export interface StkPushResponse {
  transaction_id: string;
  checkout_request_id: string;
}

export interface SessionInfo {
  hotspot_username: string;
  hotspot_password: string;
  expires_at: string;
}

export interface PaymentStatus {
  public_id: string;
  status: 'pending' | 'success' | 'reconciled' | 'failed' | 'timeout';
  amount: string;
  mpesa_receipt: string;
  result_desc: string;
  plan_name: string;
  session_active: boolean;
  session: SessionInfo | null;
  /** The state that lets the portal stop spinning. `pending` before payment,
   *  then `connecting` -> `active`, or `failed` if we took the money but couldn't
   *  build the connection. Without this the portal could not tell "still connecting"
   *  from "failed forever" and span indefinitely after a paid-but-unprovisioned. */
  provisioning: 'pending' | 'connecting' | 'active' | 'failed';
  /** Customer-facing, non-empty only when provisioning === 'failed'. Leads with
   *  "your payment is safe" because that is what they are actually afraid of. */
  provision_message: string;
}

export interface VoucherRedeemResponse {
  detail: string;
  hotspot_username: string;
  hotspot_password: string;
  expires_at: string;
}

const BASE = import.meta.env.VITE_API_BASE_URL ?? '';

export class ApiError extends Error {
  constructor(
    public status: number,
    public body: unknown
  ) {
    super(typeof body === 'object' && body && 'detail' in body ? String((body as { detail: unknown }).detail) : `HTTP ${status}`);
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const resp = await fetch(`${BASE}/api/v1${path}`, {
    headers: { 'Content-Type': 'application/json' },
    ...init,
  });
  const body = resp.status === 204 ? null : await resp.json().catch(() => null);
  if (!resp.ok) throw new ApiError(resp.status, body);
  return body as T;
}

/**
 * Plans are tenant-scoped and the API fails closed: without tenant context it
 * returns nothing rather than every ISP's plans. Context comes from the router
 * the customer is connected to (the hotspot login page passes ?router=<id>),
 * or from the ISP's subdomain in production.
 */
export function listPlans(routerId?: number | null): Promise<{ results: Plan[] }> {
  return request(`/plans/${routerId ? `?router=${routerId}` : ''}`);
}

export function initiateStkPush(params: {
  phone: string;
  plan_id: number;
  mac?: string;
  router_id?: number | null;
}): Promise<StkPushResponse> {
  return request('/payments/stk-push/', { method: 'POST', body: JSON.stringify(params) });
}

export function getPaymentStatus(transactionId: string): Promise<PaymentStatus> {
  return request(`/payments/status/${transactionId}/`);
}

/** Re-attempt a connection the customer already paid for. Money doesn't move; it just
 *  re-drives provisioning after a failure. */
export function retryProvision(transactionId: string): Promise<{ detail: string }> {
  return request(`/payments/status/${transactionId}/retry/`, { method: 'POST' });
}

export interface DeviceStatus {
  found: boolean;
  expired?: boolean;
  active?: boolean;
  plan_id?: number;
  plan_name?: string;
  expires_at?: string;
}

/** The device's latest session, so a returning/expired customer lands on renewal
 *  instead of a cold plan list. Returns no phone (MAC is spoofable — see the view). */
export interface Branding {
  name_for_customers: string;
  tagline: string;
  logo: string;
  primary_color: string;
  accent_color: string;
  support_phone: string;
  support_email: string;
  portal_template: string;
  background_image: string;
  portal_language: string;
  post_purchase_redirect: string;
}

/** The ISP's brand for this router/subdomain — so the portal wears their name, logo and
 *  colours, not the generic WIFI.OS. */
export function getBranding(routerId?: number | null): Promise<Branding> {
  return request(`/branding/${routerId ? `?router=${routerId}` : ''}`);
}

export function getDeviceStatus(mac: string, routerId?: number | null): Promise<DeviceStatus> {
  const q = new URLSearchParams({ mac });
  if (routerId) q.set('router', String(routerId));
  return request(`/payments/device-status/?${q}`);
}

export function redeemVoucher(params: {
  code: string;
  mac?: string;
  router_id?: number | null;
}): Promise<VoucherRedeemResponse> {
  return request('/vouchers/redeem/', { method: 'POST', body: JSON.stringify(params) });
}
