/**
 * Typed API client. Model types come from the OpenAPI schema generated by the
 * backend (`npm run generate:api` after `manage.py spectacular --file schema.yml`),
 * so the portal can never silently drift from the server contract.
 */

import type { components } from './schema';

export type Plan = components['schemas']['Plan'];

export interface StkPushResponse {
  transaction_id: string;
  checkout_request_id: string;
}

export interface SessionInfo {
  hotspot_username: string;
  hotspot_password: string;
  expires_at: string;
}

export interface PaymentStatus {
  public_id: string;
  status: 'pending' | 'success' | 'reconciled' | 'failed' | 'timeout';
  amount: string;
  mpesa_receipt: string;
  result_desc: string;
  session_active: boolean;
  session: SessionInfo | null;
}

export interface VoucherRedeemResponse {
  detail: string;
  hotspot_username: string;
  hotspot_password: string;
  expires_at: string;
}

const BASE = import.meta.env.VITE_API_BASE_URL ?? '';

export class ApiError extends Error {
  constructor(
    public status: number,
    public body: unknown
  ) {
    super(typeof body === 'object' && body && 'detail' in body ? String((body as { detail: unknown }).detail) : `HTTP ${status}`);
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const resp = await fetch(`${BASE}/api/v1${path}`, {
    headers: { 'Content-Type': 'application/json' },
    ...init,
  });
  const body = resp.status === 204 ? null : await resp.json().catch(() => null);
  if (!resp.ok) throw new ApiError(resp.status, body);
  return body as T;
}

/**
 * Plans are tenant-scoped and the API fails closed: without tenant context it
 * returns nothing rather than every ISP's plans. Context comes from the router
 * the customer is connected to (the hotspot login page passes ?router=<id>),
 * or from the ISP's subdomain in production.
 */
export function listPlans(routerId?: number | null): Promise<{ results: Plan[] }> {
  return request(`/plans/${routerId ? `?router=${routerId}` : ''}`);
}

export function initiateStkPush(params: {
  phone: string;
  plan_id: number;
  mac?: string;
  router_id?: number | null;
}): Promise<StkPushResponse> {
  return request('/payments/stk-push/', { method: 'POST', body: JSON.stringify(params) });
}

export function getPaymentStatus(transactionId: string): Promise<PaymentStatus> {
  return request(`/payments/status/${transactionId}/`);
}

export function redeemVoucher(params: {
  code: string;
  mac?: string;
  router_id?: number | null;
}): Promise<VoucherRedeemResponse> {
  return request('/vouchers/redeem/', { method: 'POST', body: JSON.stringify(params) });
}
