/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/campaigns/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Creating a campaign immediately queues the bulk send. */
        get: operations["notifications_campaigns_list"];
        put?: never;
        /** @description Creating a campaign immediately queues the bulk send. */
        post: operations["notifications_campaigns_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/campaigns/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Creating a campaign immediately queues the bulk send. */
        get: operations["notifications_campaigns_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications_messages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/messages/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications_messages_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/status/{public_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Portal polls this after STK push until status leaves 'pending'. */
        get: operations["payments_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/stk-push/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Portal: start an M-Pesa payment. Returns a public_id to poll. */
        post: operations["payments_stk_push_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin UI: live transaction feed. */
        get: operations["payments_transactions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/transactions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin UI: live transaction feed. */
        get: operations["payments_transactions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public can list/retrieve active plans (captive portal); staff manage them. */
        get: operations["plans_list"];
        put?: never;
        /** @description Public can list/retrieve active plans (captive portal); staff manage them. */
        post: operations["plans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public can list/retrieve active plans (captive portal); staff manage them. */
        get: operations["plans_retrieve"];
        /** @description Public can list/retrieve active plans (captive portal); staff manage them. */
        put: operations["plans_update"];
        post?: never;
        /** @description Public can list/retrieve active plans (captive portal); staff manage them. */
        delete: operations["plans_destroy"];
        options?: never;
        head?: never;
        /** @description Public can list/retrieve active plans (captive portal); staff manage them. */
        patch: operations["plans_partial_update"];
        trace?: never;
    };
    "/api/v1/routers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["routers_list"];
        put?: never;
        post: operations["routers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["routers_retrieve"];
        put: operations["routers_update"];
        post?: never;
        delete: operations["routers_destroy"];
        options?: never;
        head?: never;
        patch: operations["routers_partial_update"];
        trace?: never;
    };
    "/api/v1/routers/{id}/active_sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["routers_active_sessions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routers/{id}/test_connection/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["routers_test_connection_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sessions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/suspend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sessions_suspend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hotspot customers (non-staff users) with session summary for the admin UI. */
        get: operations["subscribers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hotspot customers (non-staff users) with session summary for the admin UI. */
        get: operations["subscribers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vouchers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vouchers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vouchers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vouchers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vouchers/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["vouchers_generate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vouchers/redeem/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Portal: redeem a printed voucher code. */
        post: operations["vouchers_redeem_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `all` - All clients
         *     * `active` - Clients with an active session
         *     * `expired` - Clients whose sessions have expired
         * @enum {string}
         */
        AudienceEnum: "all" | "active" | "expired";
        Campaign: {
            readonly id: number;
            name: string;
            channel?: components["schemas"]["ChannelEnum"];
            audience?: components["schemas"]["AudienceEnum"];
            body: string;
            readonly status: components["schemas"]["CampaignStatusEnum"];
            readonly total_recipients: number;
            readonly sent_count: number;
            readonly failed_count: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `queued` - Queued
         *     * `sending` - Sending
         *     * `done` - Done
         * @enum {string}
         */
        CampaignStatusEnum: "queued" | "sending" | "done";
        /**
         * @description * `sms` - SMS
         *     * `whatsapp` - WhatsApp
         * @enum {string}
         */
        ChannelEnum: "sms" | "whatsapp";
        Message: {
            readonly id: number;
            campaign?: number | null;
            to_phone: string;
            channel?: components["schemas"]["ChannelEnum"];
            body: string;
            status?: components["schemas"]["MessageStatusEnum"];
            provider_ref?: string;
            error?: string;
            /** Format: date-time */
            sent_at?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `queued` - Queued
         *     * `sent` - Sent
         *     * `failed` - Failed
         * @enum {string}
         */
        MessageStatusEnum: "queued" | "sent" | "failed";
        PaginatedCampaignList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Campaign"][];
        };
        PaginatedMessageList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Message"][];
        };
        PaginatedPlanList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Plan"][];
        };
        PaginatedRouterList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Router"][];
        };
        PaginatedSessionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Session"][];
        };
        PaginatedSubscriberList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Subscriber"][];
        };
        PaginatedTransactionAdminList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TransactionAdmin"][];
        };
        PaginatedVoucherList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Voucher"][];
        };
        PatchedPlan: {
            readonly id?: number;
            name?: string;
            plan_type?: components["schemas"]["PlanTypeEnum"];
            /** Format: decimal */
            price?: string;
            /** @description Access time granted, e.g. 1:00:00 for one hour */
            duration?: string;
            readonly duration_seconds?: number;
            /** @description Blank = unlimited data */
            data_cap_mb?: number | null;
            download_kbps?: number;
            upload_kbps?: number;
            shared_users?: number;
            /** @description Hotspot user profile name on the router */
            mikrotik_profile?: string;
            description?: string;
            is_active?: boolean;
            sort_order?: number;
        };
        PatchedRouter: {
            readonly id?: number;
            /** @description Site name, e.g. 'Kibera Site A' */
            name?: string;
            /** @description WireGuard IP or public IP the server reaches the router on */
            management_host?: string;
            api_port?: number;
            username?: string;
            password?: string;
            use_tls?: boolean;
            /** @description Off by default: routers use self-signed certs */
            verify_tls?: boolean;
            provisioning_backend?: components["schemas"]["ProvisioningBackendEnum"];
            readonly status?: components["schemas"]["RouterStatusEnum"];
            /** Format: date-time */
            readonly last_seen_at?: string | null;
            is_active?: boolean;
        };
        Plan: {
            readonly id: number;
            name: string;
            plan_type?: components["schemas"]["PlanTypeEnum"];
            /** Format: decimal */
            price: string;
            /** @description Access time granted, e.g. 1:00:00 for one hour */
            duration: string;
            readonly duration_seconds: number;
            /** @description Blank = unlimited data */
            data_cap_mb?: number | null;
            download_kbps: number;
            upload_kbps: number;
            shared_users?: number;
            /** @description Hotspot user profile name on the router */
            mikrotik_profile?: string;
            description?: string;
            is_active?: boolean;
            sort_order?: number;
        };
        /**
         * @description * `hotspot` - Hotspot (prepaid)
         *     * `pppoe` - PPPoE (monthly)
         * @enum {string}
         */
        PlanTypeEnum: "hotspot" | "pppoe";
        /**
         * @description * `mikrotik_rest` - MikroTik RouterOS v7 REST
         *     * `dummy` - Dummy (dev/testing)
         * @enum {string}
         */
        ProvisioningBackendEnum: "mikrotik_rest" | "dummy";
        Router: {
            readonly id: number;
            /** @description Site name, e.g. 'Kibera Site A' */
            name: string;
            /** @description WireGuard IP or public IP the server reaches the router on */
            management_host: string;
            api_port?: number;
            username?: string;
            password?: string;
            use_tls?: boolean;
            /** @description Off by default: routers use self-signed certs */
            verify_tls?: boolean;
            provisioning_backend?: components["schemas"]["ProvisioningBackendEnum"];
            readonly status: components["schemas"]["RouterStatusEnum"];
            /** Format: date-time */
            readonly last_seen_at: string | null;
            is_active?: boolean;
        };
        /**
         * @description * `online` - Online
         *     * `offline` - Offline
         *     * `unknown` - Unknown
         * @enum {string}
         */
        RouterStatusEnum: "online" | "offline" | "unknown";
        Session: {
            readonly id: number;
            /** @default  */
            readonly phone: string;
            hotspot_username: string;
            readonly plan_name: string;
            readonly router_name: string;
            status?: components["schemas"]["SessionStatusEnum"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            expires_at: string;
            mac_address?: string;
            ip_address?: string | null;
            data_used_mb?: number;
            provision_error?: string;
        };
        /**
         * @description * `pending` - Pending provision
         *     * `active` - Active
         *     * `expired` - Expired
         *     * `suspended` - Suspended
         *     * `failed` - Provisioning failed
         * @enum {string}
         */
        SessionStatusEnum: "pending" | "active" | "expired" | "suspended" | "failed";
        /**
         * @description * `pending` - Pending
         *     * `success` - Success
         *     * `failed` - Failed
         *     * `timeout` - Timeout
         *     * `reconciled` - Success (reconciled)
         * @enum {string}
         */
        Status9e7Enum: "pending" | "success" | "failed" | "timeout" | "reconciled";
        Subscriber: {
            readonly id: number;
            phone: string;
            name?: string;
            email?: string;
            /** Format: date-time */
            date_joined?: string;
            /** Format: date-time */
            readonly last_session_expires: string;
            readonly active_sessions: number;
        };
        TokenObtainPair: {
            phone: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TransactionAdmin: {
            readonly id: number;
            /** Format: uuid */
            readonly public_id: string;
            phone: string;
            readonly plan_name: string;
            /** Format: decimal */
            amount: string;
            status?: components["schemas"]["Status9e7Enum"];
            mpesa_receipt?: string;
            checkout_request_id?: string | null;
            result_code?: number | null;
            result_desc?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            callback_received_at?: string | null;
        };
        TransactionStatus: {
            /** Format: uuid */
            readonly public_id: string;
            status?: components["schemas"]["Status9e7Enum"];
            /** Format: decimal */
            amount: string;
            mpesa_receipt?: string;
            result_desc?: string;
            readonly session_active: boolean;
            /**
             * @description Hotspot credentials for the paying device — the portal submits these to
             *     the MikroTik link-login-only endpoint to connect the customer automatically.
             */
            readonly session: {
                [key: string]: unknown;
            } | null;
        };
        Voucher: {
            readonly id: number;
            code: string;
            plan: number;
            readonly plan_name: string;
            /** Format: uuid */
            batch_id?: string;
            status?: components["schemas"]["VoucherStatusEnum"];
            /** Format: date-time */
            redeemed_at?: string | null;
            printed?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `unused` - Unused
         *     * `redeemed` - Redeemed
         *     * `expired` - Expired
         *     * `void` - Void
         * @enum {string}
         */
        VoucherStatusEnum: "unused" | "redeemed" | "expired" | "void";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    notifications_campaigns_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCampaignList"];
                };
            };
        };
    };
    notifications_campaigns_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Campaign"];
                "application/x-www-form-urlencoded": components["schemas"]["Campaign"];
                "multipart/form-data": components["schemas"]["Campaign"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
        };
    };
    notifications_campaigns_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this campaign. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
        };
    };
    notifications_messages_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessageList"];
                };
            };
        };
    };
    notifications_messages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this message. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    payments_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionStatus"];
                };
            };
        };
    };
    payments_stk_push_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payments_transactions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTransactionAdminList"];
                };
            };
        };
    };
    payments_transactions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionAdmin"];
                };
            };
        };
    };
    plans_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlanList"];
                };
            };
        };
    };
    plans_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Plan"];
                "application/x-www-form-urlencoded": components["schemas"]["Plan"];
                "multipart/form-data": components["schemas"]["Plan"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
        };
    };
    plans_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
        };
    };
    plans_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Plan"];
                "application/x-www-form-urlencoded": components["schemas"]["Plan"];
                "multipart/form-data": components["schemas"]["Plan"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
        };
    };
    plans_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    plans_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPlan"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPlan"];
                "multipart/form-data": components["schemas"]["PatchedPlan"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
        };
    };
    routers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRouterList"];
                };
            };
        };
    };
    routers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Router"];
                "application/x-www-form-urlencoded": components["schemas"]["Router"];
                "multipart/form-data": components["schemas"]["Router"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Router"];
                };
            };
        };
    };
    routers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this router. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Router"];
                };
            };
        };
    };
    routers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this router. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Router"];
                "application/x-www-form-urlencoded": components["schemas"]["Router"];
                "multipart/form-data": components["schemas"]["Router"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Router"];
                };
            };
        };
    };
    routers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this router. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this router. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRouter"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRouter"];
                "multipart/form-data": components["schemas"]["PatchedRouter"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Router"];
                };
            };
        };
    };
    routers_active_sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this router. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Router"];
                };
            };
        };
    };
    routers_test_connection_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this router. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Router"];
                "application/x-www-form-urlencoded": components["schemas"]["Router"];
                "multipart/form-data": components["schemas"]["Router"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Router"];
                };
            };
        };
    };
    sessions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSessionList"];
                };
            };
        };
    };
    sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this session. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    sessions_suspend_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this session. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Session"];
                "application/x-www-form-urlencoded": components["schemas"]["Session"];
                "multipart/form-data": components["schemas"]["Session"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subscribers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubscriberList"];
                };
            };
        };
    };
    subscribers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscriber"];
                };
            };
        };
    };
    vouchers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVoucherList"];
                };
            };
        };
    };
    vouchers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this voucher. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voucher"];
                };
            };
        };
    };
    vouchers_generate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Voucher"];
                "application/x-www-form-urlencoded": components["schemas"]["Voucher"];
                "multipart/form-data": components["schemas"]["Voucher"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voucher"];
                };
            };
        };
    };
    vouchers_redeem_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
