# Generated by Django 5.2.16 on 2026-07-10 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_activate_existing_operators'),
        ('payments', '0003_alter_transaction_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone', models.CharField(help_text='M-Pesa number to pay', max_length=12)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('mpesa_reference', models.CharField(blank=True, max_length=30)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('sale', 'Sale (gross)'), ('commission', 'Platform commission'), ('base_fee', 'Monthly platform fee'), ('pppoe_fee', 'PPPoE per-user fee'), ('payout', 'Payout withdrawal'), ('adjustment', 'Manual adjustment')], db_index=True, max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(blank=True, max_length=7)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.transaction')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billing.payout')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operator', 'created_at'], name='billing_led_operato_b323a2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('transaction__isnull', False)), fields=('transaction', 'entry_type'), name='ledger_unique_tx_entry_type'), models.UniqueConstraint(condition=models.Q(('period', ''), _negated=True), fields=('operator', 'entry_type', 'period'), name='ledger_unique_periodic_fee')],
            },
        ),
    ]
