# Generated by Django 5.2.16 on 2026-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payout',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payout',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank (EFT/Pesalink)')], default='mpesa', max_length=6),
        ),
        migrations.AlterField(
            model_name='payout',
            name='mpesa_reference',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='payout',
            name='phone',
            field=models.CharField(blank=True, help_text='M-Pesa number to pay', max_length=12),
        ),
    ]
