# Generated by Django 5.2.16 on 2026-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payout_bank_account_name_payout_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='platform_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
