# Generated by Django 5.2.16 on 2026-07-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payout_platform_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'Sale (gross)'), ('commission', 'Platform commission'), ('base_fee', 'Monthly platform fee'), ('pppoe_fee', 'PPPoE per-user fee'), ('setup_fee', 'One-time setup fee'), ('payout', 'Payout withdrawal'), ('adjustment', 'Manual adjustment')], db_index=True, max_length=12),
        ),
    ]
