# Generated by Django 5.2.16 on 2026-07-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_ledgerentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='paybill',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa (B2C, to a phone)'), ('paybill', 'M-Pesa Paybill (B2B)'), ('bank', 'Bank (EFT/Pesalink)')], default='mpesa', max_length=8),
        ),
    ]
