# Generated by Django 5.2.16 on 2026-07-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_payout_paybill_alter_payout_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='payout',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
