# Generated by Django 5.2.16 on 2026-07-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_ledgerentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='settlement',
            field=models.CharField(choices=[('platform', 'Held by WIFI.OS'), ('direct', 'Paid straight to the ISP')], db_index=True, default='platform', max_length=8),
        ),
    ]
