# Generated by Django 5.2.16 on 2026-07-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_ledgerentry_settlement'),
        ('core', '0016_operator_previous_slug_operator_slug_changed_at'),
        ('notifications', '0008_messagingsettings_alert_phones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bundle', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('checkout_request_id', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', "Awaiting the customer's PIN"), ('success', 'Paid'), ('failed', 'Failed or cancelled'), ('timeout', 'No response from M-Pesa')], db_index=True, default='pending', max_length=10)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=32)),
                ('result_desc', models.CharField(blank=True, max_length=200)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('reconcile_attempts', models.PositiveSmallIntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('topup', 'Top-up (STK)'), ('grant', 'Granted by the platform'), ('sms', 'SMS sent'), ('commission', 'Commission on a direct-settled sale'), ('base_fee', 'Monthly platform fee'), ('pppoe_fee', 'PPPoE per-user fee'), ('refund', 'Refund'), ('adjustment', 'Manual adjustment')], db_index=True, max_length=12)),
                ('period', models.CharField(blank=True, max_length=7)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_charges', to='notifications.message')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
                ('topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billing.topup')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operator', 'created_at'], name='billing_pla_operato_064077_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('message',), name='platform_one_charge_per_message'), models.UniqueConstraint(condition=models.Q(('topup__isnull', False)), fields=('topup',), name='platform_one_credit_per_topup'), models.UniqueConstraint(condition=models.Q(('period', ''), _negated=True), fields=('operator', 'reason', 'period'), name='platform_unique_periodic_fee')],
            },
        ),
    ]
