# Generated by Django 5.2.16 on 2026-07-15 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_topup_platformledgerentry'),
        ('core', '0017_operator_payment_gateway_and_webhook_token'),
        ('notifications', '0009_carry_sms_credits_to_platform_account'),
        ('payments', '0010_transaction_gateway_transaction_settlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformledgerentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_fees', to='payments.transaction'),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='reason',
            field=models.CharField(choices=[('topup', 'Top-up (STK)'), ('grant', 'Granted by the platform'), ('sms', 'SMS sent'), ('commission', 'Commission on a direct-settled sale'), ('base_fee', 'Monthly platform fee'), ('pppoe_fee', 'PPPoE per-user fee'), ('setup_fee', 'One-time onboarding fee'), ('refund', 'Refund'), ('adjustment', 'Manual adjustment')], db_index=True, max_length=12),
        ),
        migrations.AddConstraint(
            model_name='platformledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction__isnull', False)), fields=('transaction',), name='platform_one_commission_per_sale'),
        ),
    ]
