# Generated by Django 5.2.16 on 2026-07-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_platformledgerentry_transaction_and_more'),
        ('core', '0018_operator_billing_warned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pppoe_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('direct_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sms', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withheld_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('paid', 'Paid')], db_index=True, default='outstanding', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('operator', 'period'), name='one_platform_invoice_per_month')],
            },
        ),
    ]
