# Generated by Django 5.2.16 on 2026-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_platforminvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='paybill_account',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
