# Generated by Django 5.2.17 on 2026-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_payout_paybill_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminvoice',
            name='ai_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='reason',
            field=models.CharField(choices=[('topup', 'Top-up (STK)'), ('grant', 'Granted by the platform'), ('sms', 'SMS sent'), ('commission', 'Commission on a direct-settled sale'), ('base_fee', 'Monthly platform fee'), ('pppoe_fee', 'PPPoE per-user fee'), ('setup_fee', 'One-time onboarding fee'), ('ai_pro', 'Pro AI subscription'), ('refund', 'Refund'), ('adjustment', 'Manual adjustment')], db_index=True, max_length=12),
        ),
    ]
