# Generated by Django 5.2.16 on 2026-07-11 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_operator_is_platform_owned'),
        ('ops', '0003_alter_ticket_subscriber'),
        ('provisioning', '0006_router_architecture_router_board_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('mode', models.CharField(choices=[('ap', 'AP (PTMP sector)'), ('ptp', 'Point-to-point'), ('ptmp', 'Point-to-multipoint')], default='ap', max_length=6)),
                ('band', models.CharField(blank=True, help_text='e.g. 5GHz, 2.4GHz', max_length=30)),
                ('frequency', models.CharField(blank=True, max_length=30)),
                ('azimuth', models.PositiveSmallIntegerField(blank=True, help_text='degrees', null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=0, help_text='Max clients this AP should carry (0 = unset)')),
                ('ssid', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.equipment')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provisioning.router')),
            ],
            options={
                'ordering': ['tower__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly, KES', max_digits=10)),
                ('download_kbps', models.PositiveIntegerField()),
                ('upload_kbps', models.PositiveIntegerField()),
                ('burst_download_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('burst_upload_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('burst_threshold_download_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('burst_threshold_upload_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('burst_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('data_cap_gb', models.PositiveIntegerField(blank=True, help_text='Fair-use cap in GB; blank = unlimited', null=True)),
                ('mikrotik_profile', models.CharField(help_text='The /ppp/profile name pushed to the router', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.CharField(blank=True, max_length=200)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pppoe_username', models.CharField(max_length=60, unique=True)),
                ('pppoe_password', models.CharField(max_length=60)),
                ('static_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('fibre', 'Fibre'), ('ethernet', 'Ethernet'), ('wireless_ptp', 'Wireless PTP'), ('wireless_ptmp', 'Wireless PTMP')], default='fibre', max_length=15)),
                ('status', models.CharField(choices=[('pending_install', 'Pending installation'), ('active', 'Active'), ('suspended', 'Suspended (overdue)'), ('disabled', 'Disabled')], db_index=True, default='pending_install', max_length=15)),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month, 1-28')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Running credit; unpaid invoices reduce it', max_digits=12)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('access_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='pppoe.accesspoint')),
                ('cpe_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpe_clients', to='ops.equipment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pppoe_clients', to='provisioning.router')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='pppoe.serviceplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_points', to='pppoe.tower'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=24, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pppoe.client')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('client', 'period_start'), name='pppoe_invoice_unique_client_period')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['operator', 'status'], name='pppoe_clien_operato_0ed3fd_idx'),
        ),
    ]
