# Generated by Django 5.2.16 on 2026-07-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_operator_suspension_reason'),
        ('pppoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='expiry_reminded_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PppoeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive_prune_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_expiry_reminder_hours', models.JSONField(blank=True, default=list)),
                ('fup_alert_percents', models.JSONField(blank=True, default=list)),
                ('auto_generate_invoices', models.BooleanField(default=True)),
                ('invoice_prefix', models.CharField(default='INV', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_settings', to='core.operator')),
            ],
        ),
    ]
