# Generated by Django 5.2.16 on 2026-07-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_operator_suspension_reason'),
        ('pppoe', '0002_client_expiry_reminded_on_pppoesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='last_online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='session_uptime',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='usage_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='wan_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('snapshot_rx', models.BigIntegerField(default=0)),
                ('snapshot_tx', models.BigIntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('fup_alerted', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_periods', to='pppoe.client')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['operator', 'period_start'], name='pppoe_clien_operato_71e379_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'period_start'), name='pppoe_usage_unique_client_period')],
            },
        ),
    ]
