# Generated by Django 5.2.16 on 2026-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppoe', '0003_client_is_online_client_last_online_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='outage_credit_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
