# Generated by Django 5.2.16 on 2026-08-08 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_status_changed_at(apps, schema_editor):
    """Seed status_changed_at from updated_at for existing clients. It's the best available
    proxy for "when did this account last change state", so the churn-ageing rule has a
    sane starting point instead of NULL (which would make every existing suspended account
    invisible to it forever)."""
    Client = apps.get_model("pppoe", "Client")
    Client.objects.filter(status_changed_at__isnull=True).update(
        status_changed_at=models.F("updated_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_operator_payout_phone_and_more'),
        ('pppoe', '0004_client_outage_credit_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pppoesettings',
            name='churn_after_suspended_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('pending_install', 'Pending installation'), ('active', 'Active'), ('suspended', 'Suspended (overdue)'), ('cancelled', 'Cancelled (churned)'), ('disabled', 'Disabled')], db_index=True, default='pending_install', max_length=15),
        ),
        migrations.CreateModel(
            name='ClientLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(db_index=True, max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('event', models.CharField(choices=[('activated', 'Activated'), ('suspended', 'Suspended (overdue)'), ('restored', 'Restored (paid up)'), ('cancelled', 'Cancelled (churned)'), ('reactivated', 'Reactivated (won back)')], db_index=True, max_length=15)),
                ('from_status', models.CharField(blank=True, max_length=15)),
                ('to_status', models.CharField(blank=True, max_length=15)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to='pppoe.client')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['operator', 'event', 'occurred_at'], name='pppoe_clien_operato_53a44d_idx')],
            },
        ),
        migrations.RunPython(backfill_status_changed_at, migrations.RunPython.noop),
    ]
