# Generated by Django 5.2.17 on 2026-08-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppoe', '0005_client_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='connection_type',
            field=models.CharField(choices=[('pppoe', 'PPPoE'), ('static', 'Static IP')], db_index=True, default='pppoe', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='pppoe_password',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='pppoe_username',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
