# Generated by Django 5.2.17 on 2026-08-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibre', '0001_initial'),
        ('pppoe', '0006_client_connection_type_alter_client_pppoe_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fibre_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fibre_clients', to='fibre.fibrepoint'),
        ),
    ]
