# Generated by Django 5.2.17 on 2026-08-20 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_operator_enforce_staff_2fa'),
        ('fibre', '0001_initial'),
        ('ops', '0005_ticket_gps_lat_ticket_gps_lng'),
        ('pppoe', '0007_client_fibre_point'),
        ('provisioning', '0015_alter_router_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['operator', '-created_at'], name='pppoe_clien_operato_f0806a_idx'),
        ),
    ]
