# Generated by Django 5.2.16 on 2026-07-08 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('void', 'Void')], db_index=True, default='unused', max_length=10)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('printed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.operator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='plans.plan')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
