# Generated by Django 5.2.16 on 2026-07-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriber'),
        ('vouchers', '0002_alter_voucher_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriber'),
        ),
    ]
