# Generated by Django 5.2.17 on 2026-08-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0030_operator_enforce_staff_2fa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FibrePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('olt_pop', 'OLT / POP'), ('cabinet', 'Cabinet (FDT)'), ('splice_closure', 'Splice closure'), ('splitter', 'Splitter'), ('odp', 'ODP'), ('pole', 'Pole'), ('handhole', 'Handhole'), ('other', 'Other')], db_index=True, default='odp', max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs attention'), ('down', 'Down')], db_index=True, default='ok', max_length=16)),
                ('port_capacity', models.PositiveSmallIntegerField(default=0)),
                ('splitter_ratio', models.CharField(blank=True, choices=[('1:2', '1:2'), ('1:4', '1:4'), ('1:8', '1:8'), ('1:16', '1:16'), ('1:32', '1:32'), ('1:64', '1:64')], max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
            options={
                'ordering': ['type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='FibreSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cable_type', models.CharField(choices=[('adss', 'ADSS (aerial)'), ('buried', 'Buried'), ('drop', 'Drop')], default='adss', max_length=8)),
                ('fibre_count', models.PositiveSmallIntegerField(default=0, help_text='Cores in this cable')),
                ('length_m', models.PositiveIntegerField(blank=True, help_text='Run length, metres', null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs attention'), ('down', 'Down')], db_index=True, default='ok', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spans_out', to='fibre.fibrepoint')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
                ('to_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spans_in', to='fibre.fibrepoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fibrepoint',
            index=models.Index(fields=['operator', 'is_active'], name='fibre_fibre_operato_0478ec_idx'),
        ),
        migrations.AddIndex(
            model_name='fibrespan',
            index=models.Index(fields=['operator', 'is_active'], name='fibre_fibre_operato_4b52bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='fibrespan',
            constraint=models.CheckConstraint(condition=models.Q(('from_point', models.F('to_point')), _negated=True), name='fibre_span_no_self_loop'),
        ),
    ]
