# Generated by Django 5.2.16 on 2026-07-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0003_activate_existing_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=12)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='core.operator')),
            ],
            options={
                'indexes': [models.Index(fields=['operator', 'phone'], name='accounts_su_operato_23f847_idx')],
                'constraints': [models.UniqueConstraint(fields=('operator', 'phone'), name='subscriber_unique_operator_phone')],
            },
        ),
    ]
