# Generated by Django 5.2.16 on 2026-07-11 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_purge_customer_user_rows'),
        ('core', '0004_operator_is_platform_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_owner', 'Platform owner'), ('platform_support', 'Platform support (read-only)'), ('tenant_owner', 'ISP owner'), ('tenant_manager', 'ISP manager'), ('tenant_support', 'ISP support (read-only)')], db_index=True, default='tenant_owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='operator',
            field=models.ForeignKey(blank=True, help_text="The ISP this user belongs to (their 'home' tenant).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.operator'),
        ),
    ]
