# Generated by Django 5.2.16 on 2026-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_mfadevice_recoverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
