# Generated by Django 5.2.17 on 2026-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_mfa_reset_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_owner', 'Platform owner'), ('platform_support', 'Platform support (read-only)'), ('tenant_owner', 'ISP owner'), ('tenant_admin', 'ISP administrator'), ('tenant_care', 'Customer care'), ('tenant_technician', 'Technician')], db_index=True, default='tenant_owner', max_length=20),
        ),
    ]
