# Generated by Django 5.2.17 on 2026-08-17 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_must_change_password'),
        ('core', '0030_operator_enforce_staff_2fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('platform_owner', 'Platform owner'), ('platform_support', 'Platform support (read-only)'), ('tenant_owner', 'ISP owner'), ('tenant_admin', 'ISP administrator'), ('tenant_care', 'Customer care'), ('tenant_technician', 'Technician')], max_length=20)),
                ('capabilities', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_configs', to='core.operator')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operator', 'role'), name='uniq_operator_role_config')],
            },
        ),
    ]
