# Generated by Django 5.2.17 on 2026-08-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_operatorroleconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
