# Generated by Django 5.2.16 on 2026-07-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_branding_background_image_branding_portal_language_and_more'),
        ('payments', '0010_transaction_gateway_transaction_settlement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=12)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('adjust', 'Manual adjustment'), ('expire', 'Expired')], max_length=8)),
                ('points', models.IntegerField(help_text='Signed: + earned, - redeemed')),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='loyalty.loyaltyaccount')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='payments.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('spend_per_point', models.PositiveIntegerField(default=100)),
                ('points_per_threshold', models.PositiveIntegerField(default=1)),
                ('min_redeem_points', models.PositiveIntegerField(default=100)),
                ('value_per_point', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_settings', to='core.operator')),
            ],
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['operator', '-points_balance'], name='loyalty_loy_operato_6e42ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.UniqueConstraint(fields=('operator', 'phone'), name='one_loyalty_account_per_operator_phone'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'earn')), fields=('transaction',), name='one_earn_per_transaction'),
        ),
    ]
