# Generated by Django 5.2.16 on 2026-07-08 18:40

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0001_initial'),
        ('plans', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Site name, e.g. 'Kibera Site A'", max_length=80)),
                ('management_host', models.CharField(help_text='WireGuard IP or public IP the server reaches the router on', max_length=100)),
                ('api_port', models.PositiveIntegerField(default=443)),
                ('username', models.CharField(default='admin', max_length=60)),
                ('password', apps.core.fields.EncryptedTextField(blank=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('verify_tls', models.BooleanField(default=False, help_text='Off by default: routers use self-signed certs')),
                ('provisioning_backend', models.CharField(choices=[('mikrotik_rest', 'MikroTik RouterOS v7 REST'), ('dummy', 'Dummy (dev/testing)')], default='mikrotik_rest', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotspot_username', models.CharField(max_length=60)),
                ('hotspot_password', models.CharField(blank=True, max_length=60)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending provision'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('failed', 'Provisioning failed')], db_index=True, default='pending', max_length=10)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_used_mb', models.PositiveIntegerField(default=0)),
                ('provision_error', models.CharField(blank=True, max_length=255)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.operator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='plans.plan')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='provisioning.router')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='payments.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('transaction__isnull', False), ('voucher__isnull', False), _connector='OR'), name='session_has_payment_source')],
            },
        ),
    ]
