# Generated by Django 5.2.16 on 2026-07-10 17:11

import apps.provisioning.models
import django.db.models.deletion
from django.db import migrations, models


def populate_tokens(apps, schema_editor):
    import secrets

    Router = apps.get_model("provisioning", "Router")
    for router in Router.objects.all():
        router.enrollment_token = secrets.token_urlsafe(32)
        router.save(update_fields=["enrollment_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0002_alter_router_operator_alter_session_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Add non-unique first, populate per-row, then enforce uniqueness
        migrations.AddField(
            model_name='router',
            name='enrollment_token',
            field=models.CharField(default=apps.provisioning.models._enrollment_token, editable=False, max_length=64),
        ),
        migrations.RunPython(populate_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='router',
            name='enrollment_token',
            field=models.CharField(default=apps.provisioning.models._enrollment_token, editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='router',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='routeros_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='router',
            name='management_host',
            field=models.CharField(blank=True, help_text='Filled automatically when the router phones home (its WireGuard/LAN IP)', max_length=100),
        ),
        migrations.AlterField(
            model_name='router',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('pending', 'Awaiting first contact'), ('unknown', 'Unknown')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='router',
            name='username',
            field=models.CharField(default='wifios', max_length=60),
        ),
        migrations.CreateModel(
            name='RouterHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='provisioning.router')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
