# Generated by Django 5.2.16 on 2026-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0004_remove_session_user_session_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='onboarding_required',
            field=models.BooleanField(default=False),
        ),
    ]
