# Generated by Django 5.2.16 on 2026-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0005_router_onboarding_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='architecture',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='router',
            name='board_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='router',
            name='identity_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='serial_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
