# Generated by Django 5.2.16 on 2026-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0006_router_architecture_router_board_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expiry_warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
