# Generated by Django 5.2.16 on 2026-07-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0007_session_expiry_warned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='data_warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
