# Generated by Django 5.2.16 on 2026-07-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0008_session_data_warned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='portal_sync_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='router',
            name='portal_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='portal_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
