# Generated by Django 5.2.16 on 2026-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0009_router_portal_sync_error_router_portal_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='clock_started',
            field=models.BooleanField(default=True),
        ),
    ]
