# Generated by Django 5.2.16 on 2026-07-15 20:23

import apps.provisioning.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_branding_background_image_branding_portal_language_and_more'),
        ('provisioning', '0010_session_clock_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device_token',
            field=models.CharField(db_index=True, default=apps.provisioning.models._device_token, max_length=64),
        ),
        migrations.CreateModel(
            name='SessionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop / computer'), ('tv', 'TV'), ('other', 'Other device')], default='other', max_length=8)),
                ('is_paying_device', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.operator')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='provisioning.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'kind'], name='provisionin_session_9f09c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'mac_address'), name='one_device_row_per_session_mac')],
            },
        ),
    ]
