# Generated by Django 5.2.16 on 2026-07-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0011_session_device_token_sessiondevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, null=True)),
                ('compensated_clients', models.PositiveIntegerField(default=0)),
                ('credited_seconds', models.PositiveIntegerField(default=0)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='provisioning.router')),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('router',), name='one_open_outage_per_router')],
            },
        ),
    ]
