# Generated by Django 5.2.16 on 2026-08-03 15:20

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0012_routeroutage'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='overlay_ip',
            field=models.GenericIPAddressField(blank=True, help_text='The /32 this router holds on the management overlay', null=True, protocol='IPv4', unique=True),
        ),
        migrations.AddField(
            model_name='router',
            name='wg_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='wg_last_handshake_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='wg_private_key',
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='router',
            name='wg_public_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
