# Generated by Django 5.2.17 on 2026-08-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0013_router_overlay_ip_router_wg_enrolled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
