# Generated by Django 5.2.17 on 2026-08-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0014_router_gps_lat_router_gps_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='router',
            options={'ordering': ['name', 'id']},
        ),
    ]
