# Generated by Django 5.2.17 on 2026-08-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_operator_enforce_staff_2fa'),
        ('provisioning', '0015_alter_router_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='uplink_mbps',
            field=models.PositiveIntegerField(blank=True, help_text='WAN uplink capacity in Mbps (for the oversubscription check)', null=True),
        ),
        migrations.CreateModel(
            name='RouterHealthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_load', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mem_used_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active_users', models.PositiveIntegerField(blank=True, null=True)),
                ('sampled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_health_samples', to='core.operator')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_samples', to='provisioning.router')),
            ],
            options={
                'ordering': ['-sampled_at'],
                'indexes': [models.Index(fields=['router', '-sampled_at'], name='provisionin_router__bb95e8_idx')],
            },
        ),
    ]
