# Generated by Django 5.2.16 on 2026-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_transaction_user_transaction_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('bill_ref', models.CharField(db_index=True, help_text='Account number typed', max_length=30)),
                ('msisdn', models.CharField(blank=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('matched', 'Matched to a client'), ('unmatched', 'No matching account')], db_index=True, max_length=10)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
