# Generated by Django 5.2.16 on 2026-07-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operator_is_platform_owned'),
        ('payments', '0005_c2bpayment'),
        ('pppoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bpayment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pppoe.client'),
        ),
        migrations.AddField(
            model_name='c2bpayment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator'),
        ),
    ]
