# Generated by Django 5.2.16 on 2026-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_c2bpayment_client_c2bpayment_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bpayment',
            name='platform_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
