# Generated by Django 5.2.16 on 2026-07-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_c2bpayment_platform_cost_transaction_platform_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2bpayment',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched to a client'), ('unmatched', 'No matching account'), ('held', 'Held — ISP not yet cleared to transact')], db_index=True, max_length=10),
        ),
    ]
