# Generated by Django 5.2.16 on 2026-07-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_c2bpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='provision_error',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
