# Generated by Django 5.2.16 on 2026-07-14 18:31

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_operator_payment_gateway_and_webhook_token'),
        ('payments', '0009_transaction_provision_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(db_index=True, default='wifios', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='settlement',
            field=models.CharField(choices=[('platform', 'Held by WIFI.OS'), ('direct', 'Paid straight to the ISP')], db_index=True, default='platform', max_length=8),
        ),
        migrations.CreateModel(
            name='GatewayCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=20)),
                ('secrets', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_credentials', to='core.operator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operator', 'gateway'), name='one_credential_per_gateway')],
            },
        ),
    ]
