# Generated by Django 5.2.17 on 2026-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_subscriber_options'),
        ('core', '0030_operator_enforce_staff_2fa'),
        ('payments', '0010_transaction_gateway_transaction_settlement_and_more'),
        ('plans', '0003_plan_tv_slots'),
        ('provisioning', '0015_alter_router_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['operator', '-created_at'], name='payments_tr_operato_fc1b24_idx'),
        ),
    ]
