# Generated by Django 5.2.17 on 2026-08-22 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_transaction_payments_tr_operato_fc1b24_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bpayment',
            name='method',
            field=models.CharField(choices=[('paybill', 'Paybill (M-Pesa C2B)'), ('cash', 'Cash'), ('mpesa_direct', 'M-Pesa (direct to ISP)'), ('bank', 'Bank transfer'), ('other', 'Other')], db_index=True, default='paybill', max_length=14),
        ),
        migrations.AddField(
            model_name='c2bpayment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='c2bpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
